BATCH_SIZE = 8
NUMBER_CLASSES = 2
INPUT_SHAPE_IMAGE = (256, 256, 3)
PROPORTION_TEST_IMAGES = 0.2
EPOCHS = 150
AUGMENTATION_DATA = True

JSON_FILE_PATH = 'data.json'
IMAGES_PATH = 'images'
MASKS_PATH = 'masks'

LEARNING_RATE = 0.0001
BACKBONE = 'resnet18'
ENCODER_WEIGHTS = 'imagenet'
OUTPUT_ACTIVATION = 'softmax'
MODEL_NAME = 'Unet'
SAVE_MODEL_EVERY_EPOCH = False

LOGS = 'logs'
SAVE_MODELS = 'save_models'
